import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const motionDuration = {
  default: '180ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const colorPickerPopoverStyles = stylex.create({
  content: {
    zIndex: 70,
    width: 'min(19rem, calc(100vw - 1.5rem))',
    maxHeight: 'min(30rem, var(--radix-popover-content-available-height))',
    overflow: 'hidden',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: 0,
    color: colors.textPrimary,
    boxShadow: '0 18px 48px rgb(0 0 0 / 24%), 0 2px 8px rgb(0 0 0 / 10%)',
    outline: 'none',
  },
  header: {
    display: 'flex',
    minHeight: '3.5rem',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    padding: '0.5rem 0.5rem 0.5rem 0.75rem',
  },
  headingGroup: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '0.625rem',
  },
  headingCopy: {
    minWidth: 0,
  },
  currentSwatch: {
    width: '1.75rem',
    height: '1.75rem',
    flex: '0 0 auto',
    borderRadius: '0.5rem',
    boxShadow: 'inset 0 0 0 1px rgb(255 255 255 / 58%), 0 0 0 1px rgb(0 0 0 / 18%)',
  },
  title: {
    margin: 0,
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 750,
    lineHeight: 1.35,
  },
  currentValue: {
    margin: '0.1rem 0 0',
    overflow: 'hidden',
    color: colors.textMuted,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.75rem',
    fontVariantNumeric: 'tabular-nums',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  closeButton: {
    display: 'inline-flex',
    minWidth: '44px',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    borderRadius: '0.625rem',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: 0,
    color: {
      default: colors.textMuted,
      ':hover': colors.textPrimary,
    },
    fontSize: '1rem',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '-3px',
    transform: {
      default: 'scale(1)',
      ':active': 'scale(0.96)',
    },
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, color, transform',
  },
  body: {
    maxHeight: 'calc(var(--radix-popover-content-available-height) - 3.5rem)',
    overflowY: 'auto',
    padding: '0.75rem',
  },
  pickerFrame: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.canvas,
    padding: '0.5rem',
    color: colors.primaryStrong,
  },
  valueGrid: {
    display: 'grid',
    margin: '0.75rem 0 0',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '0.625rem',
  },
  valueItem: {
    minWidth: 0,
    paddingInline: '0.25rem 0.75rem',
  },
  valueItemSeparated: {
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.border,
    paddingInline: '0.75rem 0.25rem',
  },
  valueLabel: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.625rem',
    fontWeight: 750,
    letterSpacing: '0.08em',
  },
  valueText: {
    margin: '0.2rem 0 0',
    overflowWrap: 'anywhere',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.75rem',
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1.4,
  },
  hint: {
    margin: '0.625rem 0 0',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.6875rem',
    lineHeight: 1.5,
  },
  arrow: {
    fill: colors.surface,
  },
});
