import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const motionDuration = {
  default: '160ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

const focusOutline = {
  default: 'none',
  ':focus-visible': `2px solid ${colors.primaryStrong}`,
} as const;

export const sceneMeldDesktopStyles = stylex.create({
  page: {
    display: 'grid',
    gap: '1rem',
  },
  launchPanel: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1.35fr) minmax(15rem, 0.65fr)',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    gap: {
      default: '2rem',
      '@media (max-width: 760px)': '1.5rem',
    },
    alignItems: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.875rem',
    backgroundColor: colors.surface,
    padding: {
      default: '2rem',
      '@media (max-width: 640px)': '1.25rem',
    },
  },
  productRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem 0.75rem',
  },
  productName: {
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 750,
    letterSpacing: '0.02em',
  },
  modeLabel: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.375rem',
    backgroundColor: colors.canvas,
    padding: '0.2rem 0.5rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  heading: {
    maxWidth: '36rem',
    margin: '0.75rem 0 0',
    color: colors.textPrimary,
    fontSize: 'clamp(1.5rem, 4vw, 2.25rem)',
    fontWeight: 650,
    letterSpacing: '-0.035em',
    lineHeight: 1.15,
  },
  description: {
    maxWidth: '40rem',
    margin: '0.875rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1rem',
    lineHeight: 1.7,
  },
  actions: {
    display: 'flex',
    marginTop: '1.25rem',
    flexWrap: 'wrap',
    gap: '0.625rem',
  },
  action: {
    display: 'inline-flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.4rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderRadius: '0.625rem',
    padding: '0.625rem 1rem',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 750,
    textDecorationLine: 'none',
    outline: focusOutline,
    outlineOffset: '2px',
    transform: {
      default: 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, border-color, color, transform',
    transitionTimingFunction: 'ease',
  },
  primaryAction: {
    borderColor: colors.primaryAction,
    backgroundColor: {
      default: colors.primaryAction,
      ':hover': colors.primaryActionHover,
    },
    color: colors.onPrimary,
  },
  secondaryAction: {
    borderColor: colors.border,
    backgroundColor: {
      default: colors.surface,
      ':hover': colors.surfaceStrong,
    },
    color: colors.textPrimary,
  },
  externalMark: {
    fontSize: '1rem',
    lineHeight: 1,
  },
  connectionCard: {
    minWidth: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.canvas,
    padding: '1.25rem',
  },
  sectionTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 750,
  },
  connectionPath: {
    display: 'grid',
    marginTop: '1rem',
    gridTemplateColumns: 'minmax(0, 1fr) auto minmax(0, 1fr)',
    alignItems: 'center',
    gap: '0.625rem',
  },
  connectionNode: {
    display: 'flex',
    minHeight: '4.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.625rem',
    backgroundColor: colors.surface,
    padding: '0.75rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 700,
    lineHeight: 1.4,
    textAlign: 'center',
  },
  connectionArrow: {
    color: colors.primaryStrong,
    fontSize: '1.25rem',
  },
  connectionNote: {
    margin: '0.875rem 0 0',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    lineHeight: 1.55,
  },
  detailsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 680px)': 'minmax(0, 1fr)',
    },
    gap: '1rem',
  },
  detailPanel: {
    minWidth: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.875rem',
    backgroundColor: colors.surface,
    padding: {
      default: '1.5rem',
      '@media (max-width: 640px)': '1.25rem',
    },
  },
  detailList: {
    display: 'grid',
    margin: '1rem 0 0',
    gap: '0.75rem',
    padding: 0,
    listStyle: 'none',
  },
  detailItem: {
    display: 'grid',
    gridTemplateColumns: '0.45rem minmax(0, 1fr)',
    gap: '0.625rem',
    alignItems: 'start',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    lineHeight: 1.55,
  },
  detailMarker: {
    width: '0.4rem',
    height: '0.4rem',
    marginTop: '0.45rem',
    borderRadius: '50%',
    backgroundColor: colors.primaryStrong,
  },
  warning: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.875rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.875rem',
    backgroundColor: colors.surfaceStrong,
    padding: {
      default: '1.25rem 1.5rem',
      '@media (max-width: 640px)': '1.125rem',
    },
  },
  warningIcon: {
    marginTop: '0.1rem',
    color: colors.primaryStrong,
    fontSize: '1.25rem',
  },
  warningText: {
    minWidth: 0,
  },
  warningDescription: {
    margin: '0.4rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    lineHeight: 1.6,
  },
});
