import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const motionDuration = {
  default: '180ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const homeStyles = stylex.create({
  page: {
    paddingBottom: '2rem',
  },
  hero: {
    display: 'grid',
    gridTemplateColumns: {
      default: '10rem minmax(0, 1fr)',
      '@media (max-width: 700px)': 'minmax(0, 1fr)',
    },
    alignItems: 'start',
    gap: {
      default: 'clamp(2rem, 4vw, 4rem)',
      '@media (max-width: 700px)': '1.75rem',
    },
    paddingBlock: {
      default: '1.5rem 4.5rem',
      '@media (max-width: 700px)': '0.75rem 3.5rem',
    },
  },
  profileRail: {
    display: 'flex',
    width: {
      default: '10rem',
      '@media (max-width: 700px)': 'auto',
    },
    marginTop: {
      default: '2rem',
      '@media (max-width: 700px)': 0,
    },
    flexDirection: 'column',
    alignItems: {
      default: 'center',
      '@media (max-width: 700px)': 'flex-start',
    },
  },
  avatar: {
    overflow: 'hidden',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '9999px',
    backgroundColor: colors.avatarPlaceholder,
    boxShadow: '0 14px 36px rgb(0 0 0 / 10%)',
  },
  avatarImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  avatarPlaceholder: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.textMuted,
    fontSize: '3rem',
    fontWeight: 600,
  },
  eyebrow: {
    margin: 0,
    color: colors.primaryStrong,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.8125rem',
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  heroTitle: {
    maxWidth: '48rem',
    margin: '0.75rem 0 0',
    color: colors.textPrimary,
    fontSize: 'clamp(2.6rem, 7vw, 5.5rem)',
    fontWeight: 550,
    letterSpacing: '-0.055em',
    lineHeight: 1.02,
    textWrap: 'balance',
  },
  heroDescription: {
    maxWidth: '44rem',
    margin: '1.5rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: {
      default: '1.125rem',
      '@media (max-width: 640px)': '1.025rem',
    },
    lineHeight: 1.8,
  },
  stackRows: {
    display: 'grid',
    marginTop: '1.75rem',
    gap: '0.25rem',
  },
  stackRow: {
    display: 'flex',
    minHeight: '32px',
    alignItems: 'center',
    gap: '0.625rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.9375rem',
  },
  inlineIcon: {
    flex: '0 0 auto',
    color: colors.textMuted,
    fontSize: '1.125rem',
  },
  externalLink: {
    color: {
      default: colors.textPrimary,
      ':hover': colors.primaryStrong,
    },
    fontWeight: 650,
    textDecorationLine: {
      default: 'none',
      ':hover': 'underline',
    },
    textUnderlineOffset: '4px',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 2fr) minmax(15rem, 1fr)',
      '@media (max-width: 860px)': 'minmax(0, 1fr)',
    },
    alignItems: 'start',
    gap: 'clamp(3rem, 7vw, 6rem)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '3rem',
  },
  sectionHeader: {
    display: 'flex',
    minHeight: '44px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
  },
  sectionTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: 'clamp(1.65rem, 4vw, 2.35rem)',
    fontWeight: 600,
    letterSpacing: '-0.035em',
    lineHeight: 1.2,
  },
  sectionLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  articleList: {
    listStyle: 'none',
    margin: '0.75rem 0 0',
    padding: 0,
  },
  articleItem: {
    display: 'grid',
    gridTemplateColumns: {
      default: '7rem minmax(0, 1fr)',
      '@media (max-width: 600px)': 'minmax(0, 1fr)',
    },
    gap: {
      default: '1.5rem',
      '@media (max-width: 600px)': '0.625rem',
    },
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingBlock: '1.5rem',
  },
  articleDate: {
    paddingTop: '0.2rem',
    color: colors.textMuted,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.75rem',
  },
  articleLink: {
    display: 'block',
    color: 'inherit',
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '5px',
  },
  articleTitle: {
    margin: 0,
    color: {
      default: colors.textPrimary,
      ':hover': colors.primaryStrong,
    },
    fontSize: '1.25rem',
    fontWeight: 650,
    letterSpacing: '-0.02em',
    lineHeight: 1.4,
    transitionDuration: motionDuration,
    transitionProperty: 'color',
  },
  articleDescription: {
    margin: '0.5rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.925rem',
    lineHeight: 1.7,
  },
  articleMeta: {
    display: 'flex',
    marginTop: '0.75rem',
    flexWrap: 'wrap',
    gap: '0.35rem 0.75rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
  },
  articleTag: {
    color: colors.primaryStrong,
  },
  topics: {
    position: {
      default: 'sticky',
      '@media (max-width: 860px)': 'static',
    },
    top: '6.5rem',
  },
  topicsIntro: {
    margin: '0.75rem 0 1.25rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.9rem',
    lineHeight: 1.7,
  },
  topicList: {
    listStyle: 'none',
    margin: 0,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    padding: 0,
  },
  topicLink: {
    display: 'flex',
    minHeight: '54px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    color: {
      default: colors.textPrimary,
      ':hover': colors.primaryStrong,
    },
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontWeight: 650,
    textDecorationLine: 'none',
    transitionDuration: motionDuration,
    transitionProperty: 'color',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  topicCount: {
    color: colors.textMuted,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.75rem',
    fontWeight: 400,
  },
});
