import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const enter = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(-0.5rem) scale(0.985)' },
  to: { opacity: 1, transform: 'translateY(0) scale(1)' },
});

const motionDuration = {
  default: '180ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const siteSearchDialogStyles = stylex.create({
  dialog: {
    width: {
      default: 'min(44rem, calc(100% - 2rem))',
      '@media (max-width: 640px)': 'calc(100% - 1rem)',
    },
    maxWidth: 'none',
    maxHeight: {
      default: 'min(44rem, calc(100dvh - 4rem))',
      '@media (max-width: 640px)': 'calc(100dvh - 1rem)',
    },
    margin: {
      default: 'clamp(2rem, 10vh, 6rem) auto auto',
      '@media (max-width: 640px)': '0.5rem auto',
    },
    overflow: 'hidden',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: {
      default: '0.875rem',
      '@media (max-width: 640px)': '0.75rem',
    },
    backgroundColor: colors.surface,
    padding: 0,
    color: colors.textPrimary,
    boxShadow: '0 24px 80px rgb(0 0 0 / 28%)',
    animationName: enter,
    animationDuration: motionDuration,
    animationTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
  visuallyHidden: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  searchHeader: {
    display: 'flex',
    minHeight: '4rem',
    alignItems: 'center',
    gap: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: {
      default: colors.border,
      ':focus-within': colors.primaryStrong,
    },
    paddingInline: {
      default: '1rem',
      '@media (max-width: 640px)': '0.75rem',
    },
    transitionDuration: motionDuration,
    transitionProperty: 'border-color',
  },
  searchIcon: {
    flex: '0 0 auto',
    color: colors.textMuted,
    fontSize: '1.35rem',
  },
  input: {
    minWidth: 0,
    minHeight: '3rem',
    flex: 1,
    borderWidth: 0,
    backgroundColor: 'transparent',
    padding: 0,
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: {
      default: '1.0625rem',
      '@media (max-width: 640px)': '1rem',
    },
    outline: 'none',
    '::placeholder': {
      color: colors.textMuted,
      opacity: 1,
    },
  },
  closeButton: {
    display: 'inline-flex',
    minWidth: '44px',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.5rem',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: 0,
    color: colors.textMuted,
    fontSize: '1.15rem',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, color',
  },
  resultRegion: {
    minHeight: {
      default: '18rem',
      '@media (max-width: 640px)': 'calc(100dvh - 9rem)',
    },
    maxHeight: {
      default: 'min(32rem, calc(100dvh - 13rem))',
      '@media (max-width: 640px)': 'calc(100dvh - 9rem)',
    },
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    padding: '0.5rem',
    scrollbarGutter: 'stable',
  },
  status: {
    display: 'flex',
    minHeight: '17rem',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.9375rem',
    lineHeight: 1.7,
    textAlign: 'center',
  },
  resultList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  resultOption: {
    cursor: 'pointer',
    borderRadius: '0.5rem',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: '0.75rem 0.875rem',
    transitionDuration: motionDuration,
    transitionProperty: 'background-color',
  },
  resultOptionActive: {
    backgroundColor: colors.surfaceStrong,
  },
  resultMeta: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '0.625rem',
  },
  resultType: {
    flex: '0 0 auto',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.3rem',
    padding: '0.05rem 0.35rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.6875rem',
    lineHeight: 1.55,
  },
  resultTitle: {
    minWidth: 0,
    overflow: 'hidden',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.975rem',
    fontWeight: 650,
    lineHeight: 1.45,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  resultParent: {
    marginTop: '0.25rem',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
    fontWeight: 600,
  },
  resultExcerpt: {
    marginTop: '0.35rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    lineHeight: 1.55,
  },
  resultMetadata: {
    marginTop: '0.35rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
    lineHeight: 1.55,
  },
  footer: {
    display: {
      default: 'flex',
      '@media (max-width: 640px)': 'none',
    },
    minHeight: '2.75rem',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingInline: '1rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
  },
  keyHints: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  keyHint: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  keycap: {
    display: 'inline-flex',
    minWidth: '1.35rem',
    minHeight: '1.35rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.25rem',
    backgroundColor: colors.surfaceStrong,
    paddingInline: '0.25rem',
    color: colors.textSecondary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.6875rem',
    lineHeight: 1,
  },
});
