import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const motionDuration = {
  default: '180ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const toolboxStyles = stylex.create({
  page: {
    paddingBottom: '2rem',
  },
  hero: {
    maxWidth: '48rem',
    paddingBlock: {
      default: '1.25rem 3rem',
      '@media (max-width: 640px)': '0.5rem 2.25rem',
    },
  },
  title: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: 'clamp(2.5rem, 7vw, 5rem)',
    fontWeight: 600,
    letterSpacing: '-0.055em',
    lineHeight: 1.05,
  },
  description: {
    maxWidth: '42rem',
    margin: '1.25rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: {
      default: '1.0625rem',
      '@media (max-width: 640px)': '1rem',
    },
    lineHeight: 1.75,
  },
  catalog: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '2rem',
  },
  searchGroup: {
    display: 'grid',
    maxWidth: '44rem',
    gap: '0.5rem',
  },
  label: {
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
  },
  searchWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  searchIcon: {
    position: 'absolute',
    left: '0.875rem',
    color: colors.textMuted,
    fontSize: '1.125rem',
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    minHeight: '48px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':focus': colors.primaryStrong,
    },
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: '0.75rem 1rem 0.75rem 2.75rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1rem',
    outline: 'none',
    boxShadow: {
      default: 'none',
      ':focus': `0 0 0 3px ${colors.primaryTransparent20}`,
    },
  },
  filters: {
    display: 'flex',
    marginTop: '1rem',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  filterButton: {
    minHeight: '44px',
    cursor: 'pointer',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '9999px',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: '0.5rem 0.875rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 650,
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, color, border-color',
  },
  filterButtonActive: {
    borderColor: colors.primaryStrong,
    backgroundColor: colors.primaryTransparent10,
    color: colors.primaryStrong,
  },
  directoryHeader: {
    display: 'flex',
    marginTop: '2rem',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem 1rem',
  },
  resultCount: {
    margin: 0,
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 650,
  },
  viewSwitcher: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: '0.25rem',
  },
  viewButton: {
    display: 'inline-flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.45rem',
    borderWidth: 0,
    borderRadius: '0.5rem',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: '0.5rem 0.75rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, color',
  },
  viewButtonActive: {
    backgroundColor: colors.primaryTransparent10,
    color: colors.primaryStrong,
  },
  toolGrid: {
    display: 'grid',
    marginTop: '1rem',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (max-width: 960px)': 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 640px)': 'minmax(0, 1fr)',
    },
    gap: '1rem',
  },
  toolList: {
    display: 'grid',
    marginTop: '1rem',
    gap: '0.625rem',
  },
  toolItem: {
    minWidth: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':hover': colors.primaryTransparent20,
      ':focus-visible': colors.primaryTransparent20,
    },
    borderRadius: '0.875rem',
    backgroundColor: {
      default: colors.surface,
      ':hover': colors.surfaceStrong,
      ':focus-visible': colors.surfaceStrong,
    },
    color: 'inherit',
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
    transitionDuration: motionDuration,
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    transitionProperty: 'background-color, border-color, transform',
  },
  gridItem: {
    display: 'grid',
    minHeight: '14rem',
    gridTemplateColumns: '3rem minmax(0, 1fr)',
    gridTemplateRows: 'auto 1fr auto',
    alignItems: 'start',
    gap: '1rem',
    padding: '1.25rem',
    transform: {
      default: 'translateY(0)',
      ':hover': 'translateY(-2px)',
      ':active': 'translateY(0)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  listItem: {
    display: 'grid',
    minHeight: '6.5rem',
    gridTemplateColumns: '3rem minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '1rem',
    padding: {
      default: '1rem 1.125rem',
      '@media (max-width: 640px)': '1rem',
    },
    transform: {
      default: 'translateX(0)',
      ':hover': 'translateX(4px)',
      ':active': 'translateX(2px)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
  },
  iconTile: {
    display: 'flex',
    width: '3rem',
    height: '3rem',
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.625rem',
    backgroundColor: colors.primaryTransparent10,
    color: colors.primaryStrong,
    fontSize: '1.5rem',
  },
  itemContent: {
    minWidth: 0,
  },
  gridContent: {
    gridColumn: '1 / -1',
    alignSelf: 'start',
  },
  itemTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: '1.125rem',
    fontWeight: 650,
    letterSpacing: '-0.015em',
  },
  itemDescription: {
    maxWidth: '36rem',
    margin: '0.4rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.925rem',
    lineHeight: 1.65,
  },
  itemEnd: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  gridEnd: {
    gridColumn: '1 / -1',
    alignSelf: 'end',
    justifyContent: 'space-between',
  },
  listEnd: {
    justifyContent: 'flex-end',
  },
  itemCategory: {
    display: 'inline-flex',
    minHeight: '1.75rem',
    alignItems: 'center',
    borderRadius: '9999px',
    backgroundColor: colors.primaryTransparent10,
    paddingInline: '0.625rem',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  listCategory: {
    display: {
      default: 'inline-flex',
      '@media (max-width: 640px)': 'none',
    },
    color: colors.textMuted,
    backgroundColor: colors.canvas,
  },
  rowArrow: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1.25rem',
    lineHeight: 1,
  },
  emptyState: {
    marginTop: '2rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: '2rem',
    textAlign: 'center',
  },
  emptyTitle: {
    color: colors.textPrimary,
    fontSize: '1.25rem',
    fontWeight: 650,
  },
  emptyDescription: {
    margin: '0.5rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  clearButton: {
    minHeight: '44px',
    marginTop: '1rem',
    cursor: 'pointer',
    borderRadius: '0.625rem',
    backgroundColor: colors.primaryAction,
    padding: '0.625rem 1rem',
    color: colors.onPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontWeight: 700,
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
});
