import { colors } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const motionDuration = {
  default: '160ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const toolUiStyles = stylex.create({
  page: {
    paddingBottom: '2rem',
  },
  header: {
    maxWidth: '48rem',
    paddingBlock: {
      default: '0.75rem 2.5rem',
      '@media (max-width: 640px)': '0.25rem 2rem',
    },
  },
  backLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  titleRow: {
    display: 'flex',
    marginTop: '0.75rem',
    alignItems: 'center',
    gap: '0.875rem',
  },
  iconTile: {
    display: 'flex',
    width: '3.25rem',
    height: '3.25rem',
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.75rem',
    backgroundColor: colors.primaryTransparent10,
    color: colors.primaryStrong,
    fontSize: '1.6rem',
  },
  title: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: 'clamp(2rem, 6vw, 3.5rem)',
    fontWeight: 600,
    letterSpacing: '-0.05em',
    lineHeight: 1.05,
  },
  description: {
    margin: '1rem 0 0',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1rem',
    lineHeight: 1.7,
  },
  privacyNote: {
    display: 'inline-flex',
    maxWidth: '48rem',
    marginTop: '1rem',
    alignItems: 'flex-start',
    gap: '0.4rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    lineHeight: 1.55,
  },
  privacyNoteIcon: {
    marginTop: '0.12rem',
  },
  workspace: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '2rem',
  },
  splitGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    gap: '1rem',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 640px)': 'minmax(0, 1fr)',
    },
    gap: '1rem',
  },
  panel: {
    minWidth: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.875rem',
    backgroundColor: colors.surface,
    padding: {
      default: '1.25rem',
      '@media (max-width: 640px)': '1rem',
    },
  },
  panelWide: {
    marginTop: '1rem',
  },
  field: {
    display: 'grid',
    gap: '0.5rem',
  },
  fieldSpaced: {
    marginTop: '1rem',
  },
  label: {
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
  },
  helper: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    lineHeight: 1.55,
  },
  input: {
    width: '100%',
    minHeight: '46px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':focus': colors.primaryStrong,
    },
    borderRadius: '0.625rem',
    backgroundColor: colors.canvas,
    padding: '0.65rem 0.75rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    outline: 'none',
    boxShadow: {
      default: 'none',
      ':focus': `0 0 0 3px ${colors.primaryTransparent20}`,
    },
  },
  colorControl: {
    display: 'flex',
    minWidth: 0,
    minHeight: '46px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':focus-within': colors.primaryStrong,
    },
    borderRadius: '0.625rem',
    backgroundColor: colors.canvas,
    boxShadow: {
      default: 'none',
      ':focus-within': `0 0 0 3px ${colors.primaryTransparent20}`,
    },
    transitionDuration: motionDuration,
    transitionProperty: 'border-color, box-shadow',
  },
  colorControlInvalid: {
    borderColor: '#b91c1c',
  },
  colorSwatchButton: {
    display: 'inline-flex',
    width: '3.25rem',
    minHeight: '44px',
    cursor: 'pointer',
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: colors.border,
    borderRadius: '0.55rem 0 0 0.55rem',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.surfaceStrong,
    },
    padding: 0,
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '-3px',
    transitionDuration: motionDuration,
    transitionProperty: 'background-color',
  },
  colorSwatch: {
    width: '1.75rem',
    height: '1.75rem',
    borderRadius: '0.45rem',
    boxShadow: 'inset 0 0 0 1px rgb(255 255 255 / 58%), 0 0 0 1px rgb(0 0 0 / 20%)',
    transform: {
      default: 'scale(1)',
      ':hover': 'scale(1.04)',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    transitionDuration: motionDuration,
    transitionProperty: 'transform',
  },
  colorTextInput: {
    minWidth: 0,
    minHeight: '44px',
    flex: 1,
    borderWidth: 0,
    backgroundColor: 'transparent',
    padding: '0.65rem 0.75rem',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.875rem',
    fontVariantNumeric: 'tabular-nums',
    outline: 'none',
  },
  select: {
    cursor: 'pointer',
  },
  textarea: {
    width: '100%',
    minHeight: '18rem',
    resize: 'vertical',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':focus': colors.primaryStrong,
    },
    borderRadius: '0.625rem',
    backgroundColor: colors.canvas,
    padding: '0.875rem',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.875rem',
    lineHeight: 1.65,
    outline: 'none',
    boxShadow: {
      default: 'none',
      ':focus': `0 0 0 3px ${colors.primaryTransparent20}`,
    },
  },
  textareaCompact: {
    minHeight: '10rem',
  },
  actions: {
    display: 'flex',
    marginTop: '1rem',
    flexWrap: 'wrap',
    gap: '0.625rem',
  },
  button: {
    display: 'inline-flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.625rem',
    backgroundColor: {
      default: colors.surface,
      ':hover': colors.surfaceStrong,
    },
    padding: '0.625rem 0.9rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 700,
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
    transform: {
      default: 'scale(1)',
      ':active': 'scale(0.98)',
    },
    transitionDuration: motionDuration,
    transitionProperty: 'background-color, color, transform',
  },
  buttonPrimary: {
    borderColor: colors.primaryAction,
    backgroundColor: {
      default: colors.primaryAction,
      ':hover': colors.primaryActionHover,
    },
    color: colors.onPrimary,
  },
  buttonDanger: {
    color: '#b91c1c',
  },
  status: {
    minHeight: '1.4rem',
    marginTop: '0.75rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
  },
  error: {
    color: '#b91c1c',
  },
  metrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(8rem, 1fr))',
    gap: '0.75rem',
  },
  metric: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.625rem',
    backgroundColor: colors.canvas,
    padding: '0.875rem',
  },
  metricValue: {
    display: 'block',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '1.35rem',
    fontWeight: 700,
    fontVariantNumeric: 'tabular-nums',
  },
  metricLabel: {
    display: 'block',
    marginTop: '0.25rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
  },
  resultList: {
    display: 'grid',
    gap: '0.75rem',
  },
  resultRow: {
    display: 'grid',
    gridTemplateColumns: {
      default: '8rem minmax(0, 1fr)',
      '@media (max-width: 520px)': 'minmax(0, 1fr)',
    },
    gap: '0.25rem 1rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    paddingBottom: '0.75rem',
  },
  resultLabel: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 700,
  },
  resultValue: {
    minWidth: 0,
    overflowWrap: 'anywhere',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.875rem',
  },
  preview: {
    display: 'flex',
    minHeight: '10rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    padding: '1.5rem',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1.25rem',
    fontWeight: 700,
    textAlign: 'center',
  },
});
