import { colors, layout } from '@/styles/tokens.stylex';
import * as stylex from '@stylexjs/stylex';

const reducedMotionDuration = {
  default: '180ms',
  '@media (prefers-reduced-motion: reduce)': '0ms',
} as const;

export const articleStyles = stylex.create({
  pageHeader: {
    maxWidth: '46rem',
    marginBottom: '3rem',
  },
  pageTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: 'clamp(2.5rem, 7vw, 4.75rem)',
    fontWeight: 500,
    letterSpacing: '-0.045em',
    lineHeight: 1.05,
  },
  pageDescription: {
    maxWidth: '42rem',
    marginTop: '1.25rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '1.0625rem',
    lineHeight: 1.75,
  },
  articleCount: {
    display: 'block',
    marginTop: '1rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
  },
  filterStatus: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
  },
  filter: {
    marginBottom: '2.5rem',
  },
  filterLabel: {
    display: 'block',
    marginBottom: '0.625rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 600,
  },
  searchRow: {
    display: 'flex',
    maxWidth: '42rem',
    alignItems: 'stretch',
    gap: '0.75rem',
  },
  searchInput: {
    minWidth: 0,
    minHeight: '46px',
    flex: 1,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':focus': colors.primaryStrong,
    },
    borderRadius: '0.625rem',
    backgroundColor: colors.surface,
    paddingInline: '0.875rem',
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    outline: {
      default: 'none',
      ':focus-visible': `3px solid ${colors.primaryTransparent20}`,
    },
  },
  searchButton: {
    minWidth: '5rem',
    minHeight: '46px',
    cursor: 'pointer',
    borderRadius: '0.625rem',
    backgroundColor: {
      default: colors.primaryAction,
      ':hover': colors.primaryActionHover,
    },
    paddingInline: '1rem',
    color: colors.onPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontWeight: 600,
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'background-color',
    outline: {
      default: 'none',
      ':focus-visible': `3px solid ${colors.primaryTransparent20}`,
    },
    outlineOffset: '2px',
  },
  filterActions: {
    display: 'flex',
    marginTop: '0.75rem',
    alignItems: 'center',
    gap: '1rem',
  },
  clearLink: {
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 600,
    textDecorationLine: {
      default: 'none',
      ':hover': 'underline',
    },
    textUnderlineOffset: '4px',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  tagList: {
    display: 'flex',
    marginTop: '1.25rem',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem',
  },
  tagLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':hover': colors.primaryStrong,
    },
    borderRadius: '9999px',
    backgroundColor: {
      default: colors.surface,
      ':hover': colors.primaryTransparent10,
    },
    paddingInline: '0.875rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    textDecorationLine: 'none',
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'border-color, background-color, color',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  tagLinkActive: {
    borderColor: colors.primaryStrong,
    backgroundColor: colors.primaryTransparent10,
    color: colors.primaryStrong,
    fontWeight: 600,
  },
  tagLinkCollapsedMobile: {
    display: {
      default: 'inline-flex',
      '@media (max-width: 640px)': 'none',
    },
  },
  tagLinkCollapsedDesktop: {
    display: 'none',
  },
  tagLinkForcedVisible: {
    display: 'inline-flex',
  },
  tagToggle: {
    display: 'inline-flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':hover': colors.primaryStrong,
    },
    borderRadius: '9999px',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.primaryTransparent10,
    },
    paddingInline: '0.875rem',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 600,
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'border-color, background-color',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  tagToggleMobileOnly: {
    display: {
      default: 'none',
      '@media (max-width: 640px)': 'inline-flex',
    },
  },
  articleList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  articleItem: {
    display: 'grid',
    gridTemplateColumns: {
      default: '9rem minmax(0, 1fr)',
      '@media (max-width: 700px)': 'minmax(0, 1fr)',
    },
    gap: {
      default: '2rem',
      '@media (max-width: 700px)': '0.75rem',
    },
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingBlock: '2rem',
  },
  articleDate: {
    paddingTop: '0.25rem',
    color: colors.textMuted,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
  },
  articleLink: {
    display: 'block',
    color: 'inherit',
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '6px',
  },
  articleTitle: {
    margin: 0,
    color: {
      default: colors.textPrimary,
      ':hover': colors.primaryStrong,
    },
    fontSize: 'clamp(1.45rem, 3vw, 2rem)',
    fontWeight: 600,
    letterSpacing: '-0.025em',
    lineHeight: 1.25,
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'color',
  },
  articleDescription: {
    maxWidth: '48rem',
    marginTop: '0.75rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.975rem',
    lineHeight: 1.75,
  },
  articleMeta: {
    display: 'flex',
    marginTop: '1rem',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem 0.875rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
  },
  inlineTag: {
    color: colors.primaryStrong,
  },
  draftBadge: {
    display: 'inline-flex',
    minHeight: '1.75rem',
    alignItems: 'center',
    borderRadius: '9999px',
    backgroundColor: colors.surfaceStrong,
    paddingInline: '0.625rem',
    color: colors.textSecondary,
    fontWeight: 600,
  },
  emptyState: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingBlock: '3rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    lineHeight: 1.75,
  },
  detailHeader: {
    maxWidth: '60rem',
    marginBottom: {
      default: '4rem',
      '@media (max-width: 640px)': '3rem',
    },
  },
  backLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    color: colors.primaryStrong,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
    fontWeight: 600,
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '3px',
  },
  detailTitle: {
    margin: '1.25rem 0 0',
    color: colors.textPrimary,
    fontSize: 'clamp(2.25rem, 5vw, 4rem)',
    fontWeight: 600,
    letterSpacing: '-0.04em',
    lineHeight: 1.12,
    textWrap: 'balance',
  },
  detailDescription: {
    maxWidth: '46rem',
    marginTop: '1.5rem',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: {
      default: '1.125rem',
      '@media (max-width: 640px)': '1.0625rem',
    },
    lineHeight: 1.72,
  },
  detailMeta: {
    display: 'flex',
    marginTop: '1.75rem',
    flexWrap: 'wrap',
    alignItems: 'center',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '1rem',
    gap: '0.625rem 1rem',
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.875rem',
  },
  detailTags: {
    display: 'flex',
    marginTop: '0.75rem',
    flexWrap: 'wrap',
    gap: '0.25rem 1rem',
  },
  detailTag: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: {
      default: 'transparent',
      ':hover': colors.primaryStrong,
    },
    color: {
      default: colors.textMuted,
      ':hover': colors.primaryStrong,
    },
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 600,
    textDecorationLine: 'none',
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'border-color, color',
    '::before': {
      content: '"#"',
    },
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  articleGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1fr) 15rem',
      '@media (max-width: 980px)': 'minmax(0, 1fr)',
    },
    alignItems: 'start',
    gap: 'clamp(2rem, 5vw, 5rem)',
  },
  prose: {
    minWidth: 0,
    maxWidth: '68ch',
    color: colors.textSecondary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif',
    fontSize: {
      default: '1.0625rem',
      '@media (max-width: 640px)': '1rem',
    },
    lineHeight: 1.85,
  },
  heading2: {
    marginTop: '4.25rem',
    marginBottom: '1.25rem',
    scrollMarginTop: `calc(${layout.headerSafeArea} + 1rem)`,
    color: colors.textPrimary,
    fontFamily: 'AlimamaFangYuan, system-ui, sans-serif',
    fontSize: 'clamp(1.75rem, 3.5vw, 2.25rem)',
    fontWeight: 650,
    letterSpacing: '-0.025em',
    lineHeight: 1.25,
    textWrap: 'balance',
  },
  heading3: {
    marginTop: '2.75rem',
    marginBottom: '0.875rem',
    scrollMarginTop: `calc(${layout.headerSafeArea} + 1rem)`,
    color: colors.textPrimary,
    fontFamily: 'AlimamaFangYuan, system-ui, sans-serif',
    fontSize: '1.375rem',
    fontWeight: 650,
    lineHeight: 1.4,
  },
  paragraph: {
    marginBlock: '1.2rem',
  },
  proseLink: {
    color: colors.primaryStrong,
    fontWeight: 600,
    textDecorationLine: 'underline',
    textDecorationThickness: '1px',
    textUnderlineOffset: '4px',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  list: {
    marginBlock: '1.25rem',
    paddingLeft: '1.4rem',
  },
  listItem: {
    marginBlock: '0.45rem',
    paddingLeft: '0.25rem',
  },
  strong: {
    color: colors.textPrimary,
    fontWeight: 700,
  },
  blockquote: {
    marginBlock: '2rem',
    borderLeftWidth: '3px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.primary,
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: '1.125rem 1.25rem',
    color: colors.textSecondary,
    fontStyle: 'normal',
  },
  divider: {
    marginBlock: '3.5rem',
    borderWidth: 0,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
  },
  inlineCode: {
    borderRadius: '0.35rem',
    backgroundColor: colors.surfaceStrong,
    padding: '0.15rem 0.4rem',
    color: colors.textPrimary,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.9em',
  },
  codeBlock: {
    maxWidth: '100%',
    marginBlock: '1.75rem',
    overflowX: 'auto',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.codeBorder,
    borderRadius: '0.75rem',
    backgroundColor: colors.codeSurface,
    padding: '1.25rem',
    color: colors.codeText,
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '0.875rem',
    lineHeight: 1.7,
  },
  codeInBlock: {
    backgroundColor: 'transparent',
    padding: 0,
    color: 'inherit',
    fontSize: 'inherit',
  },
  tableScroll: {
    maxWidth: '100%',
    marginBlock: '1.75rem',
    overflowX: 'auto',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
  },
  table: {
    width: '100%',
    minWidth: '34rem',
    borderCollapse: 'collapse',
    backgroundColor: colors.surface,
    fontSize: '0.925rem',
  },
  tableHead: {
    backgroundColor: colors.surfaceStrong,
    color: colors.textPrimary,
    textAlign: 'left',
  },
  tableCell: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    padding: '0.75rem 1rem',
    textAlign: 'left',
    verticalAlign: 'top',
  },
  image: {
    display: 'block',
    width: '100%',
    height: 'auto',
    marginBlock: '2rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
  },
  callout: {
    marginBlock: '2rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: '0.75rem',
    backgroundColor: colors.surfaceStrong,
    padding: '1.25rem',
  },
  calloutTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontWeight: 700,
  },
  calloutBody: {
    marginTop: '0.5rem',
  },
  tocAside: {
    position: 'sticky',
    top: `calc(${layout.headerSafeArea} + 1rem)`,
    display: {
      default: 'block',
      '@media (max-width: 980px)': 'none',
    },
    maxHeight: `calc(100dvh - ${layout.headerSafeArea} - 2rem)`,
    alignSelf: 'start',
    overflowY: 'auto',
    overscrollBehaviorY: 'contain',
    scrollBehavior: {
      default: 'smooth',
      '@media (prefers-reduced-motion: reduce)': 'auto',
    },
  },
  toc: {
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.border,
    paddingLeft: '1.25rem',
  },
  tocTitle: {
    margin: 0,
    color: colors.textPrimary,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 700,
  },
  tocList: {
    position: 'relative',
    listStyle: 'none',
    margin: '0.75rem 0 0',
    padding: 0,
  },
  tocIndicator: {
    position: 'absolute',
    top: 0,
    left: '-1.3125rem',
    width: '2px',
    pointerEvents: 'none',
    borderRadius: '9999px',
    backgroundColor: colors.primaryStrong,
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'transform, opacity',
    transitionTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    willChange: 'transform',
  },
  tocItem: {
    position: 'relative',
    marginBlock: '0.4rem',
  },
  tocItemNested: {
    paddingLeft: '0.875rem',
  },
  tocLink: {
    display: 'inline-block',
    color: {
      default: colors.textMuted,
      ':hover': colors.primaryStrong,
    },
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.8125rem',
    lineHeight: 1.55,
    textDecorationLine: 'none',
    transitionDuration: reducedMotionDuration,
    transitionProperty: 'color',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  tocLinkActive: {
    color: colors.primaryStrong,
    fontWeight: 700,
  },
  adjacentSection: {
    maxWidth: '70ch',
    marginTop: '4rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: '2rem',
  },
  adjacentGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 640px)': 'minmax(0, 1fr)',
    },
    gap: '1rem',
  },
  adjacentLink: {
    display: 'flex',
    minHeight: '7.5rem',
    flexDirection: 'column',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':hover': colors.primaryStrong,
    },
    borderRadius: '0.75rem',
    backgroundColor: colors.surface,
    padding: '1rem',
    color: colors.textPrimary,
    textDecorationLine: 'none',
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${colors.primaryStrong}`,
    },
    outlineOffset: '2px',
  },
  adjacentLabel: {
    color: colors.textMuted,
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: '0.75rem',
  },
  adjacentTitle: {
    marginTop: '0.5rem',
    fontSize: '1rem',
    fontWeight: 650,
    lineHeight: 1.45,
  },
});
